### ISSUE TITLE
1.19.1 support

### ISSUE THREAD

**Issue by Bluebulu998** [Linkin-Lab-Server/tweakeroo#6]
When I tried to use tweak hotkey in 1.19.1 it crashes

[20:34:21] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: field_11733
	at fi.dy.masa.malilib.util.InfoUtils.printActionbarMessage(InfoUtils.java:149) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at fi.dy.masa.malilib.util.InfoUtils.printBooleanConfigToggleMessage(InfoUtils.java:182) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at fi.dy.masa.malilib.hotkeys.KeyCallbackToggleBooleanConfigWithMessage.onKeyAction(KeyCallbackToggleBooleanConfigWithMessage.java:18) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:143) ~[malilib-fabric-1.19-0.12.1(1).jar:?]
	at net.minecraft.class_309.handler$cdn000$onKeyboardInput(class_309.java:2583) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:316) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:462) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:462) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1204) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by CivetKitty** [comment]
Same here. There is a Masa build on Curseforge, so you might go and have a look to make that compatible.
